nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ["https://kasu.surge.sh", "http://localhost:3000", "http://localhost:8000"]
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600